apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: intellij-secretstore
  namespace: intellij
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: /components/intellij-secret.json
    - name: nestedSeparator
      value: "."
    - name: multiValued
      value: "true"